version: '3'
services:
  # Application
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www

  # Web Server
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
